# Generated by Django 5.0.2 on 2024-03-01 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=200, verbose_name="Person's First Name ")),
                ('last_name', models.CharField(max_length=200, verbose_name='Last Name')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Email')),
                ('address', models.CharField(max_length=200, verbose_name='Address')),
                ('index_no', models.CharField(max_length=20, verbose_name='Index Number')),
                ('mother_name', models.CharField(max_length=200, verbose_name='Mother Name')),
                ('father_name', models.CharField(max_length=200, verbose_name='Father Name')),
            ],
            options={
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Rgann',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('string1', models.CharField(blank=True, db_comment='string1 in database', max_length=100, null=True)),
                ('datefrom', models.DateField(blank=True, null=True)),
                ('rgapattern', models.CharField(blank=True, max_length=400, null=True)),
                ('rgatext', models.CharField(blank=True, max_length=1000, null=True)),
            ],
            options={
                'managed': True,
            },
        ),
    ]
